# Generated by Django 4.1.2 on 2022-10-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0002_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
