# Generated by Django 4.1.2 on 2022-10-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0007_alter_payment_mac_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="total",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
