# Generated by Django 4.1.2 on 2022-10-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0012_student"),
    ]

    operations = [
        migrations.DeleteModel(name="Student",),
    ]
